# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AGSTools
								 A QGIS plugin
 This plugin parses an AGS file and creates a database from it
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
							  -------------------
		begin                : 2023-04-19
		copyright            : (C) 2025 by Oliver Burdekin / burdGIS
		email                : info@burdgis.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Oliver Burdekin / burdGIS'
__date__ = '2023-04-19'
__copyright__ = '(C) 2025 by Oliver Burdekin / burdGIS'


# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QVariant
from qgis.core import (QgsApplication,
					   QgsSettings,
					   QgsProcessingAlgorithm,
					   QgsProcessingParameterFile,
					   QgsProcessingParameterFileDestination,
					   QgsProcessingParameterBoolean,
					   QgsProcessingParameterString,
					   QgsProcessingParameterCrs,
					   QgsCoordinateReferenceSystem,
					   QgsVectorLayer,
					   QgsVectorLayer,
					   QgsField,
					   QgsFields,
					   QgsFeature,
					   QgsGeometry,
					   QgsPointXY,
					   QgsVectorFileWriter,
					   QgsProject,
					   QgsCoordinateTransform,
					   QgsProcessingException,
					   QgsDataSourceUri,
					   QgsMapLayer,
					   QgsProviderRegistry
						)
from qgis.utils import iface
from io import StringIO
# import sqlite3
import os
from pathlib import Path

if __package__:
	from .core.parser import AGSParser
	from .core.transformer import AGSTransformer
	from .core.exporter import CSVExporter
else:
	from core.parser import AGSParser
	from core.transformer import AGSTransformer
	from core.exporter import CSVExporter


class AGS2DBAlgorithm(QgsProcessingAlgorithm):
	"""
	This is an example algorithm that takes a vector layer and
	creates a new identical one.

	It is meant to be used as an example of how to create your own
	algorithms and explain methods and variables used to do it. An
	algorithm like this will be available in all elements, and there
	is not need for additional work.

	All Processing algorithms should extend the QgsProcessingAlgorithm
	class.
	"""

	# Constants used to refer to parameters and outputs. They will be
	# used when calling the algorithm from another algorithm, or when
	# calling from the QGIS console.

	OUTPUT = 'OUTPUT'
	INPUT = 'INPUT'
	DATA_DESC = 'DATA_DESC'
	CRS = 'CRS'
	EXPORT_CSV = 'EXPORT_CSV'
	CSV_OUTPUT_DIR = 'CSV_OUTPUT_DIR'
	CSV_OUTPUT_FOLDER_NAME = 'CSV_OUTPUT_FOLDER_NAME'
	CSV_APPEND_MODE = 'CSV_APPEND_MODE'

	def initAlgorithm(self, config):
		"""
		Here we define the inputs and output of the algorithm, along
		with some other properties.
		"""

		# We add the input vector features source. It can have any kind of
		# geometry.
		self.addParameter(
			QgsProcessingParameterFile(
				self.INPUT,
				self.tr('Input AGS file(s)'),
				
			)
		)

		self.addParameter(
			QgsProcessingParameterCrs(
				self.CRS,
				self.tr('Coordinate reference system'),
				defaultValue=QgsCoordinateReferenceSystem('EPSG:27700')
			)
		)

		# Use FileDestination parameter for proper "Save As" dialog
		self.addParameter(
			QgsProcessingParameterFileDestination(
				self.OUTPUT,
				self.tr('Output Database File'),
				fileFilter='GeoPackage (*.gpkg);;SpatiaLite (*.sqlite)'
				
			)
		)

		self.addParameter(
			QgsProcessingParameterString(
				self.DATA_DESC,
				self.tr('Description of proposed use of data'),
				defaultValue='',
				optional=True
			)
		)

		self.addParameter(
			QgsProcessingParameterBoolean(
				self.EXPORT_CSV,
				self.tr('\nCreate CSV Files for plotting in PowerBI'),
				defaultValue=False
			)
		)

		csv_output_dir_param = QgsProcessingParameterFile(
			self.CSV_OUTPUT_DIR,
			self.tr('Output CSV Database Folder (existing or new)'),
			behavior=QgsProcessingParameterFile.Folder,
			optional=True
		)
		csv_output_dir_param.setMetadata({
			'widget_wrapper': {
				'depends_on': self.EXPORT_CSV,
				'depends_on_value': True
			}
		})
		self.addParameter(csv_output_dir_param)

		csv_output_folder_name_param = QgsProcessingParameterString(
			self.CSV_OUTPUT_FOLDER_NAME,
			self.tr('Folder name of CSV database (leave blank if appending to existing folder)'),
			defaultValue='',
			optional=True
		)
		csv_output_folder_name_param.setMetadata({
			'widget_wrapper': {
				'depends_on': self.EXPORT_CSV,
				'depends_on_value': True
			}
		})
		self.addParameter(csv_output_folder_name_param)

		csv_append_param = QgsProcessingParameterBoolean(
			self.CSV_APPEND_MODE,
			self.tr('Append to existing CSV files'),
			defaultValue=False,
			optional=True
		)
		csv_append_param.setMetadata({
			'widget_wrapper': {
				'depends_on': self.EXPORT_CSV,
				'depends_on_value': True
			}
		})
		self.addParameter(csv_append_param)

	def parse_ags_file(self, file_contents):

		def is_numeric(value):
			"""Utility function to check if value can be converted to a number."""
			try:
				float(value)
				return True
			except ValueError:
				return False

		lines = file_contents.split('\n')
		data = {}
		current_group = None
		headers = []

		for line in lines:
			if not line.strip():
				continue

			temp = line.strip().split('","')
			temp = [item.strip('"') for item in temp]

			if temp[0] == 'GROUP':
				current_group = temp[1]
				data[current_group] = []  # Initialize the group
			elif temp[0] == 'HEADING':
				headers = temp[1:]
			elif temp[0] == 'UNIT':
				if current_group and headers:
					unit_values = temp[1:]
					# Pad missing values with empty strings
					if len(unit_values) < len(headers):
						unit_values.extend([''] * (len(headers) - len(unit_values)))
					# Validate and skip invalid unit rows
					if all(not value.strip() for value in unit_values):  # All empty or whitespace
						continue
					data[f"{current_group}_units"] = dict(zip(headers, unit_values))
			elif temp[0] == 'DATA':
				# Add data rows to the current group
				if current_group and headers:
					record = dict(zip(headers, temp[1:]))
					data[current_group].append(record)

		# Detect column types for each group independently
		column_types = {}
		for group_name, records in data.items():
			if group_name.endswith("_units"):
				continue

			if records:
				group_headers = list(records[0].keys())
				column_types[group_name] = {}
				for header in group_headers:
					all_numeric = all(is_numeric(record.get(header)) for record in records if record.get(header))
					column_types[group_name][header] = "REAL" if all_numeric else "TEXT"

		return data, column_types

	def createLOCAFeatures(self, records, column_types, crs, feedback):
		"""
		Create a memory point layer for LOCA features using available coordinate fields.
		- Checks for LOCA_NATE/LOCA_NATN, LOCA_LOCX/LOCA_LOCY, LOCA_LAT/LOCA_LON in that order.
		- Logs if features or all fail to have coordinates.
		- Reprojects if using LAT/LON from EPSG:4326 to target CRS.
		"""
		# Determine which coordinate fields are present and use them in priority:
		coord_priority = [
			('LOCA_NATE', 'LOCA_NATN'),
			('LOCA_LOCX', 'LOCA_LOCY'),
			('LOCA_LAT', 'LOCA_LON')
		]
		
		chosen_coords = None
		for pair in coord_priority:
			# Check if both fields exist
			if all(p in column_types['LOCA'] for p in pair):
				x_field, y_field = pair
				# Check if there's at least one record with non-empty coordinates
				has_data = False
				for record in records:
					x_val = record.get(x_field)
					y_val = record.get(y_field)
					if x_val and x_val.strip() != '' and y_val and y_val.strip() != '':
						has_data = True
						break

				if has_data:
					chosen_coords = pair
					break

		# Create the layer
		layer = QgsVectorLayer("Point?crs={}".format(crs.authid()), "LOCA", "memory")
		data_provider = layer.dataProvider()

		# Add fields
		fields = QgsFields()
		for field_name, field_type in column_types['LOCA'].items():
			qgis_field_type = QVariant.Double if field_type == "REAL" else QVariant.String
			fields.append(QgsField(field_name, qgis_field_type))
		data_provider.addAttributes(fields)
		layer.updateFields()

		if chosen_coords is None:
			feedback.reportError("No recognized coordinate fields found in LOCA. Creating empty point layer.")
			return layer

		x_field, y_field = chosen_coords

		# Set up coordinate transform if needed
		# If we're using LAT/LON, we assume they're in EPSG:4326 and must transform to chosen CRS
		transform = None
		if chosen_coords == ('LOCA_LAT', 'LOCA_LON'):
			source_crs = QgsCoordinateReferenceSystem('EPSG:4326')
			transform = QgsCoordinateTransform(source_crs, crs, QgsProject.instance())

		features_with_coords = 0
		for record in records:
			# Get attributes
			attrs = []
			for header, ftype in column_types['LOCA'].items():
				val = record.get(header)
				if ftype == "REAL":
					if val is None or val.strip() == '':
						attrs.append(None)
					else:
						attrs.append(float(val))
				else:
					attrs.append(val if val is not None else None)

			# Attempt to get coordinates
			x_val = record.get(x_field)
			y_val = record.get(y_field)
			if x_val is None or x_val.strip() == '' or y_val is None or y_val.strip() == '':
				# No coordinates for this feature
				feedback.pushInfo(f"LOCA feature missing coordinates: {record}")
				# We still add the feature but without geometry
				
				f = QgsFeature()
				f.setAttributes(attrs)
				f.setGeometry(None)
				data_provider.addFeature(f)
				continue

			# Convert to float
			x = float(x_val)
			y = float(y_val)

			# Transform if LAT/LON
			if transform:
				pt = transform.transform(QgsPointXY(y, x))  # careful with order: LAT = Y, LON = X
			else:
				pt = QgsPointXY(x, y)

			f = QgsFeature()
			f.setAttributes(attrs)
			f.setGeometry(QgsGeometry.fromPointXY(pt))
			data_provider.addFeature(f)
			features_with_coords += 1

		layer.updateExtents()

		if features_with_coords == 0:
			feedback.reportError("No LOCA features had valid coordinates. The LOCA layer will have no geometries.")

		return layer

	def create_database_connection(self, output_path, feedback):
		# Only works for gpkg
		md = QgsProviderRegistry.instance().providerMetadata("ogr")
		conn = md.createConnection(output_path, {})
		conn_name = os.path.splitext(os.path.basename(output_path))[0]
		md.saveConnection(conn, conn_name)


		# Refresh database connections in the Browser Panel
		iface.browserModel().refresh()

	def add_svg_paths(self, feedback):
	
		svg_path = os.path.join(os.path.dirname(__file__), 'styles', 'svg')
		svg_paths = QgsApplication.svgPaths()
		if svg_path not in svg_paths:
			svg_paths.append(svg_path)
			QgsApplication.setDefaultSvgPaths(svg_paths)
			feedback.pushInfo("Added custom SVG path for symbols.")

	def loadLayerAndApplyStyle(self, output_path, table_name, qml_path, feedback):
		# Load the layer using OGR provider. GPK and SpatiaLite are supported.

		layer_path = f"{output_path}|layername={table_name}"
		layer = QgsVectorLayer(layer_path, table_name, "ogr")

		if not layer.isValid():
			feedback.pushInfo(f"Table '{table_name}' cannot be added.")
			return None

		QgsProject.instance().addMapLayer(layer)
		feedback.pushInfo(f"Added '{table_name}' layer to the project.")

		if layer.isValid() and os.path.exists(qml_path):
			layer.loadNamedStyle(qml_path)
			layer.triggerRepaint()
			feedback.pushInfo("Applied QML style to the LOCA layer.")

		if iface:
			iface.layerTreeView().refreshLayerSymbology(layer.id())

		return layer

	def processAlgorithm(self, parameters, context, feedback):
		# Define the output path
		output_path = self.parameterAsString(parameters, self.OUTPUT, context)
		if not output_path:
			raise QgsProcessingException("DB output file is required.")
		ext = os.path.splitext(output_path)[1].lower()
		feedback.pushInfo(f"Writing all groups GeoPackage to: {output_path}")

		# Remove existing GeoPackage if it exists
		if os.path.exists(output_path):
			os.remove(output_path)
			feedback.pushInfo(f"Removed existing GeoPackage at: {output_path}")

		# Load AGS4 file contents
		ags_file_path = self.parameterAsFile(parameters, self.INPUT, context)
		with open(ags_file_path, 'r') as ags_file:
			file_contents = ags_file.read()

		# Get chosen CRS
		crs = self.parameterAsCrs(parameters, self.CRS, context)
		data_desc = self.parameterAsString(parameters, self.DATA_DESC, context)
		data_desc = (data_desc or '').strip()

		# Parse the AGS file
		data, column_types = self.parse_ags_file(file_contents)

		ags_filename = Path(ags_file_path).name
		db_filename = Path(output_path).name
		proj_id = ''
		if 'PROJ' in data:
			for record in data['PROJ']:
				proj_val = str(record.get('PROJ_ID', '') or '').strip()
				if proj_val:
					proj_id = proj_val
					break
		
		# For AGS2DB, source_file format: ags_filename|db_filename|project_id
		# This provides full traceability: where data came from (AGS), where it went (DB), and what project
		source_file_value = f"{ags_filename}|{db_filename}|{proj_id}" if proj_id else f"{ags_filename}|{db_filename}"

		# Ensure provenance fields exist across all DB tables
		for group_name, records in data.items():
			if group_name.endswith("_units"):
				continue
			column_types.setdefault(group_name, {})['source_file'] = 'TEXT'
			for record in records:
				if not str(record.get('source_file', '') or '').strip():
					record['source_file'] = source_file_value

		# Inject user-supplied description into PROJ records for DB output.
		if 'PROJ' in data:
			for record in data['PROJ']:
				record['data_desc'] = data_desc
			column_types.setdefault('PROJ', {})['data_desc'] = 'TEXT'

		first_layer = True
		transform_context = context.transformContext()

		for group_name, records in data.items():
			if group_name.endswith("_units"):
				continue  # Skip unit tables

			feedback.pushInfo(f"Processing group: {group_name}")

			if group_name.upper() == "LOCA":
				# Create spatial LOCA layer
				layer = self.createLOCAFeatures(records, column_types, crs, feedback)

			else:
				# Non-spatial layer
				layer = QgsVectorLayer("NoGeometry", group_name, "memory")
				data_provider = layer.dataProvider()

				# Add fields
				fields = QgsFields()
				for field_name, field_type in column_types[group_name].items():
					qgis_field_type = QVariant.Double if field_type == "REAL" else QVariant.String
					fields.append(QgsField(field_name, qgis_field_type))
				data_provider.addAttributes(fields)
				layer.updateFields()

				# Populate layer
				for record in records:
					feature = QgsFeature()
					attrs = []
					for header, ftype in column_types[group_name].items():
						val = record.get(header)
						if ftype == "REAL":
							if val is None or val.strip() == '':
								attrs.append(None)
							else:
								attrs.append(float(val))
						else:
							attrs.append(val if val is not None else None)
					feature.setAttributes(attrs)
					data_provider.addFeature(feature)
				layer.updateExtents()

			# Export layer
			options = QgsVectorFileWriter.SaveVectorOptions()
			options.driverName = "GPKG"
			if ext == '.gpkg':
				options.driverName = "GPKG"
			elif ext == '.sqlite':
				options.driverName = "SQLite"
				options.driverOptions = ["SPATIALITE=YES"]
			else:
				raise QgsProcessingException("Unsupported file format selected.")

			options.layerName = group_name
			options.fileEncoding = "UTF-8"
			# Geometry type will be derived automatically for V3 method

			if first_layer:
				options.actionOnExistingFile = QgsVectorFileWriter.ActionOnExistingFile.CreateOrOverwriteFile
			else:
				options.actionOnExistingFile = QgsVectorFileWriter.ActionOnExistingFile.CreateOrOverwriteLayer

			error, newFilename, newLayer, errorMessage = QgsVectorFileWriter.writeAsVectorFormatV3(
				layer,
				output_path,
				transform_context,
				options
			)

			if error == QgsVectorFileWriter.WriterError.NoError:
				feedback.pushInfo(f"Successfully wrote group '{group_name}' to GeoPackage.")
			else:
				feedback.reportError(f"Error writing group '{group_name}' to GeoPackage: {errorMessage}")

			first_layer = False

		feedback.pushInfo("ALL GROUPS WRITTEN - DB CREATED")

		# After the writing is done, call the helper functions:
		self.add_svg_paths(feedback)

		qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'loca_spatial.qml')

    	# Load and style the LOCA layer
		self.loadLayerAndApplyStyle(output_path, "LOCA", qml_path, feedback)

		self.create_database_connection(output_path, feedback)

		# ====== CSV EXPORT (conditional) ======
		export_csv = self.parameterAsBool(parameters, self.EXPORT_CSV, context)
		if export_csv:
			csv_parent_dir = self.parameterAsString(parameters, self.CSV_OUTPUT_DIR, context)
			csv_output_folder_name = self.parameterAsString(parameters, self.CSV_OUTPUT_FOLDER_NAME, context)
			append_mode = self.parameterAsBool(parameters, self.CSV_APPEND_MODE, context)
			
			if not csv_parent_dir:
				raise QgsProcessingException("CSV export enabled but no parent folder specified.")

			folder_name = (csv_output_folder_name or "").strip()
			if folder_name:
				csv_output_dir = os.path.join(csv_parent_dir, folder_name)
			else:
				# If appending, use selected folder directly; otherwise create default subfolder.
				if append_mode:
					csv_output_dir = csv_parent_dir
				else:
					csv_output_dir = os.path.join(csv_parent_dir, 'ags_csv_export')
			
			# Determine overwrite/append behavior from explicit user selection
			if os.path.exists(csv_output_dir):
				csv_files = [f for f in os.listdir(csv_output_dir) if f.endswith('.csv')]
				if csv_files:
					if append_mode:
						feedback.pushInfo("Appending to existing CSVs...")
					else:
						feedback.pushInfo("Overwriting existing CSVs...")
			else:
				if append_mode:
					feedback.pushInfo("Append mode selected, but no existing CSV folder found. New CSV files will be created.")
			
			feedback.pushInfo(f"Exporting AGS to CSV folder: {csv_output_dir}")
			
			try:
				# Parse AGS file
				parser = AGSParser(ags_file_path)
				parser.load()
				feedback.pushInfo("AGS file loaded for CSV export")
				
				# Transform and export
				source_file = Path(ags_file_path).name
				transformer = AGSTransformer(parser, source_file, data_desc=data_desc)
				exporter = CSVExporter(csv_output_dir, append_mode=append_mode)
				
				# Tables to export (from ags_2_csv.py TABLES list)
				tables = [
					"proj", "loca", "samp", "bkfl", "geol", "detl", "ispt", "core", "weth", "frac",
					"hdph", "wins", "wstg", "wstd", "mong", "mond", "dcpg", "dcpt", "dprg", "icbr",
					"ipid", "ivan", "chis", "ptim", "lpdn", "llpl", "grat", "grag", "mcvg", "lnmc",
					"mcvt", "cbrg", "cbrt", "cmpg", "cmpt", "cong", "cons", "shbg", "shbt", "trig",
					"trit", "gchm", "eres"
				]
				
				for table in tables:
					if feedback.isCanceled():
						feedback.pushInfo("CSV export cancelled by user.")
						break
					
					method_name = f"transform_{table}"
					transform_method = getattr(transformer, method_name, None)
					if transform_method is None:
						feedback.pushInfo(f"Skipping {table}: no transform method")
						continue
					
					try:
						df = transform_method()
						exporter.write(table, df, source_file)
						feedback.pushInfo(f"Wrote {table}.csv ({len(df)} rows)")
					except Exception as e:
						feedback.reportError(f"Error transforming {table}: {str(e)}")
				
				exporter.write_manifest()
				feedback.pushInfo("CSV export complete - wrote manifest.csv")
				
			except Exception as e:
				feedback.reportError(f"CSV export failed: {str(e)}")

		return {self.OUTPUT: output_path}
	
	def processing_log(self, message):
		"""
		Logs a message to the Processing log.
		"""
		self.logMessage(message)

	def name(self):
		"""
		Returns the algorithm name, used for identifying the algorithm. This
		string should be fixed for the algorithm, and must not be localised.
		The name should be unique within each provider. Names should contain
		lowercase alphanumeric characters only and no spaces or other
		formatting characters.
		"""
		return 'AGS2DB'

	def displayName(self):
		"""
		Returns the translated algorithm name, which should be used for any
		user-visible display of the algorithm name.
		"""
		return self.tr(self.name())

	def group(self):
		"""
		Returns the name of the group this algorithm belongs to. This string
		should be localised.
		"""
		return self.tr(self.groupId())

	def groupId(self):
		"""
		Returns the unique ID of the group this algorithm belongs to. This
		string should be fixed for the algorithm, and must not be localised.
		The group id should be unique within each provider. Group id should
		contain lowercase alphanumeric characters only and no spaces or other
		formatting characters.
		"""
		return ''

	def tr(self, string):
		return QCoreApplication.translate('Processing', string)

	def createInstance(self):
		return AGS2DBAlgorithm()
